### ISSUE TITLE
Not an issue, but request for example with CDK

### ISSUE THREAD

**Issue by tomilaurell** [martinjlowm/dependency-packer-webpack-plugin#1]
Thanks for excellent plugin! 

Would you be able to share a bit how you would build your project using this library? I guess you have two/three-phase build where
1. "npm run build" first compile with tsc and then builds and pack the project with webpack.
2. Then you might have "npm run deploy" which does the CDK-deploy when the cdk-files points to the already built lambda output folders as you name them (.webpack/lambda_name)

I assume that you have used this library yourself already somewhere, but that might not be open-sourced. Do you have (or know) any example project using this plugin with AWS-CDK?

**Comment by martinjlowm** [comment]
Hi @tomilaurell,


Thanks for using it 😄 

The plugin taps into Webpack and when it's done bundling entry points, it runs through all require's, builds a package.json and runs `npm i`/`yarn`/`pnpm i`.

So, what you need, is an existing Webpack config where entry points are explicit, add this plugin and it will install dependencies in the entry output directory. Usually, it's within `.webpack/<entrypoint>/...`. As for aws-cdk (assuming you want to inject the entrypoint as a Lambda function), you can reference this directory as is described here: https://docs.aws.amazon.com/cdk/api/latest/docs/aws-lambda-readme.html

I have a bunch of projects that use this, but unfortunately they aren't open source, but I suppose I can extract a practical example which I can include in the README. Perhaps by Monday :)

**Comment by tomilaurell** [comment]
I appreciate that very much. The practical example adds significant value to this repo too.

**Comment by martinjlowm** [comment]
I added an example under `examples/` last night - let me know what you think :)

**Comment by tomilaurell** [comment]
I already made some tests yesterday. I'm actually having some issues, but the reason can be anywhere. I don't know why, but lerna/yarn_workspaces/typescript/webpack does not recognise correctly references internal modules. Specifically, I'm trying to include your plugin to be used here:
https://github.com/tomilaurell/cdk-multi-module-project-template

I'm not satisfied how things are now build (stack-code vs lambda-code), but it works. Your plugin should make everything much more pleasant to work with.

For some yet unknown reason, the referenced packages were not recognized as typescript or compiled code. But I'm working on it more.

**Comment by tomilaurell** [comment]
But anyway, the example you provided is good so I will close this issue as resolved :-)

**Comment by martinjlowm** [comment]
In my example, I use Babel with a typescript preset that Webpack runs through the babel-loader. I suppose you can do the same, thus the pipeline becomes: TypeScript source » Babel » Webpack bundling » Dependency packing (through this plugin) » aws-cdk deploy with a Lambda asset reference to `.webpack/<entry>`. You can start by verifying Webpack with the Babel loader on your source and see if that works and then move on to using this plugin together with aws-cdk.

FYI. Your repo is not up-to-date - I see no use of Webpack there :)
